# Site settings
auto: false
name: MISDAY
title: MISDAY
url: "http://www.misday.com"
baseurl: "/"
#timezone: Asia/Chongqing
description: ""

# Your information
email: vin@misday.com
author: Vincent
avatar: "https://avatars0.githubusercontent.com/u/1163889?v=3&s=460"
profile: ""

# Social network configuration
#twitter_username: twitter_username
github_username:  susemm

# Comment Service (Disqus or ถเหต)
#  choose one and un-comment the line to active it
disqus_shortname: misday-1   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

#pygments: true
permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
# - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: [CNAME, npm-debug.log, node_modules]

google_analytics: UA-28333273-1
